-- Role: openlandusers
-- DROP ROLE openlandusers;
CREATE ROLE openlandusers
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

-- Role: openlandadmin
-- DROP ROLE openlandadmin;
CREATE ROLE openlandadmin LOGIN
  ENCRYPTED PASSWORD 'md55d9d5946359e9d556a1f153a664588d2'
  SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION;

-- Role: openlanduser1
-- DROP ROLE openlanduser1;
CREATE ROLE openlanduser1 LOGIN
  ENCRYPTED PASSWORD 'md547a0f2910add4de172d0747bcaf19a75'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION CONNECTION LIMIT 8;
GRANT openlandusers TO openlanduser1;
