# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'document.ui'
#
# Created: Fri Nov 08 20:21:13 2013
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_DialogDocument(object):
    def setupUi(self, DialogDocument):
        DialogDocument.setObjectName(_fromUtf8("DialogDocument"))
        DialogDocument.resize(520, 480)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/folders.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogDocument.setWindowIcon(icon)
        DialogDocument.setSizeGripEnabled(True)
        DialogDocument.setModal(True)
        self.verticalLayout = QtGui.QVBoxLayout(DialogDocument)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.treeWidget = QtGui.QTreeWidget(DialogDocument)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.verticalLayout.addWidget(self.treeWidget)
        self.toolBox = QtGui.QToolBox(DialogDocument)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.pageAttributes = QtGui.QWidget()
        self.pageAttributes.setGeometry(QtCore.QRect(0, 0, 486, 402))
        self.pageAttributes.setObjectName(_fromUtf8("pageAttributes"))
        self.formLayout_2 = QtGui.QFormLayout(self.pageAttributes)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label = QtGui.QLabel(self.pageAttributes)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.comboBoxDocumentType = QtGui.QComboBox(self.pageAttributes)
        self.comboBoxDocumentType.setObjectName(_fromUtf8("comboBoxDocumentType"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBoxDocumentType)
        self.label_2 = QtGui.QLabel(self.pageAttributes)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.lineEditName = QtGui.QLineEdit(self.pageAttributes)
        self.lineEditName.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditName.setObjectName(_fromUtf8("lineEditName"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditName)
        self.label_3 = QtGui.QLabel(self.pageAttributes)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.lineEditSeries = QtGui.QLineEdit(self.pageAttributes)
        self.lineEditSeries.setInputMask(_fromUtf8(""))
        self.lineEditSeries.setObjectName(_fromUtf8("lineEditSeries"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditSeries)
        self.label_4 = QtGui.QLabel(self.pageAttributes)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.lineEditNumberDoc = QtGui.QLineEdit(self.pageAttributes)
        self.lineEditNumberDoc.setObjectName(_fromUtf8("lineEditNumberDoc"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEditNumberDoc)
        self.label_5 = QtGui.QLabel(self.pageAttributes)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.dateEditDateDoc = QtGui.QDateEdit(self.pageAttributes)
        self.dateEditDateDoc.setCalendarPopup(True)
        self.dateEditDateDoc.setObjectName(_fromUtf8("dateEditDateDoc"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.dateEditDateDoc)
        self.label_6 = QtGui.QLabel(self.pageAttributes)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.lineEdItissueOrgan = QtGui.QLineEdit(self.pageAttributes)
        self.lineEdItissueOrgan.setObjectName(_fromUtf8("lineEdItissueOrgan"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEdItissueOrgan)
        self.label_7 = QtGui.QLabel(self.pageAttributes)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_7)
        self.lineEditNumberReg = QtGui.QLineEdit(self.pageAttributes)
        self.lineEditNumberReg.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditNumberReg.setObjectName(_fromUtf8("lineEditNumberReg"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.lineEditNumberReg)
        self.label_8 = QtGui.QLabel(self.pageAttributes)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtGui.QLabel(self.pageAttributes)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_9)
        self.dateEditDurationStarted = QtGui.QDateEdit(self.pageAttributes)
        self.dateEditDurationStarted.setCalendarPopup(True)
        self.dateEditDurationStarted.setObjectName(_fromUtf8("dateEditDurationStarted"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.FieldRole, self.dateEditDurationStarted)
        self.label_10 = QtGui.QLabel(self.pageAttributes)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_2.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_10)
        self.dateEditDurationStopped = QtGui.QDateEdit(self.pageAttributes)
        self.dateEditDurationStopped.setCalendarPopup(True)
        self.dateEditDurationStopped.setObjectName(_fromUtf8("dateEditDurationStopped"))
        self.formLayout_2.setWidget(9, QtGui.QFormLayout.FieldRole, self.dateEditDurationStopped)
        self.label_11 = QtGui.QLabel(self.pageAttributes)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_2.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_11)
        self.lineEditRegister = QtGui.QLineEdit(self.pageAttributes)
        self.lineEditRegister.setObjectName(_fromUtf8("lineEditRegister"))
        self.formLayout_2.setWidget(10, QtGui.QFormLayout.FieldRole, self.lineEditRegister)
        self.label_12 = QtGui.QLabel(self.pageAttributes)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_2.setWidget(11, QtGui.QFormLayout.LabelRole, self.label_12)
        self.lineEditDescDoc = QtGui.QLineEdit(self.pageAttributes)
        self.lineEditDescDoc.setObjectName(_fromUtf8("lineEditDescDoc"))
        self.formLayout_2.setWidget(11, QtGui.QFormLayout.FieldRole, self.lineEditDescDoc)
        self.label_13 = QtGui.QLabel(self.pageAttributes)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_2.setWidget(12, QtGui.QFormLayout.LabelRole, self.label_13)
        self.lineEditIssueOrganCode = QtGui.QLineEdit(self.pageAttributes)
        self.lineEditIssueOrganCode.setObjectName(_fromUtf8("lineEditIssueOrganCode"))
        self.formLayout_2.setWidget(12, QtGui.QFormLayout.FieldRole, self.lineEditIssueOrganCode)
        self.dateEditDateReg = QtGui.QDateEdit(self.pageAttributes)
        self.dateEditDateReg.setCalendarPopup(True)
        self.dateEditDateReg.setObjectName(_fromUtf8("dateEditDateReg"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.FieldRole, self.dateEditDateReg)
        self.label_14 = QtGui.QLabel(self.pageAttributes)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_2.setWidget(13, QtGui.QFormLayout.LabelRole, self.label_14)
        self.lineEditCreateUser = QtGui.QLineEdit(self.pageAttributes)
        self.lineEditCreateUser.setReadOnly(True)
        self.lineEditCreateUser.setObjectName(_fromUtf8("lineEditCreateUser"))
        self.formLayout_2.setWidget(13, QtGui.QFormLayout.FieldRole, self.lineEditCreateUser)
        self.label_15 = QtGui.QLabel(self.pageAttributes)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_2.setWidget(14, QtGui.QFormLayout.LabelRole, self.label_15)
        self.lineEditCreateDate = QtGui.QLineEdit(self.pageAttributes)
        self.lineEditCreateDate.setReadOnly(True)
        self.lineEditCreateDate.setObjectName(_fromUtf8("lineEditCreateDate"))
        self.formLayout_2.setWidget(14, QtGui.QFormLayout.FieldRole, self.lineEditCreateDate)
        self.toolBox.addItem(self.pageAttributes, _fromUtf8(""))
        self.pageAppliedFiles = QtGui.QWidget()
        self.pageAppliedFiles.setGeometry(QtCore.QRect(0, 0, 96, 79))
        self.pageAppliedFiles.setObjectName(_fromUtf8("pageAppliedFiles"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.pageAppliedFiles)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.treeWidgetAppliedFiles = QtGui.QTreeWidget(self.pageAppliedFiles)
        self.treeWidgetAppliedFiles.setObjectName(_fromUtf8("treeWidgetAppliedFiles"))
        self.horizontalLayout_2.addWidget(self.treeWidgetAppliedFiles)
        self.toolBox.addItem(self.pageAppliedFiles, _fromUtf8(""))
        self.verticalLayout.addWidget(self.toolBox)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButtonSelect = QtGui.QPushButton(DialogDocument)
        self.pushButtonSelect.setEnabled(False)
        self.pushButtonSelect.setStatusTip(_fromUtf8(""))
        self.pushButtonSelect.setWhatsThis(_fromUtf8(""))
        self.pushButtonSelect.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/symbol_check.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonSelect.setIcon(icon1)
        self.pushButtonSelect.setAutoDefault(False)
        self.pushButtonSelect.setDefault(True)
        self.pushButtonSelect.setObjectName(_fromUtf8("pushButtonSelect"))
        self.horizontalLayout.addWidget(self.pushButtonSelect)
        self.pushButtonAdd = QtGui.QPushButton(DialogDocument)
        self.pushButtonAdd.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/symbol_add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonAdd.setIcon(icon2)
        self.pushButtonAdd.setAutoDefault(False)
        self.pushButtonAdd.setObjectName(_fromUtf8("pushButtonAdd"))
        self.horizontalLayout.addWidget(self.pushButtonAdd)
        self.pushButtonEdit = QtGui.QPushButton(DialogDocument)
        self.pushButtonEdit.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/edit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonEdit.setIcon(icon3)
        self.pushButtonEdit.setAutoDefault(False)
        self.pushButtonEdit.setObjectName(_fromUtf8("pushButtonEdit"))
        self.horizontalLayout.addWidget(self.pushButtonEdit)
        self.pushButtonDel = QtGui.QPushButton(DialogDocument)
        self.pushButtonDel.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/symbol_remove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonDel.setIcon(icon4)
        self.pushButtonDel.setAutoDefault(False)
        self.pushButtonDel.setObjectName(_fromUtf8("pushButtonDel"))
        self.horizontalLayout.addWidget(self.pushButtonDel)
        self.pushButtonSave = QtGui.QPushButton(DialogDocument)
        self.pushButtonSave.setEnabled(False)
        self.pushButtonSave.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonSave.setIcon(icon5)
        self.pushButtonSave.setAutoDefault(False)
        self.pushButtonSave.setObjectName(_fromUtf8("pushButtonSave"))
        self.horizontalLayout.addWidget(self.pushButtonSave)
        self.pushButtonRefresh = QtGui.QPushButton(DialogDocument)
        self.pushButtonRefresh.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonRefresh.setIcon(icon6)
        self.pushButtonRefresh.setAutoDefault(False)
        self.pushButtonRefresh.setObjectName(_fromUtf8("pushButtonRefresh"))
        self.horizontalLayout.addWidget(self.pushButtonRefresh)
        self.pushButtonClose = QtGui.QPushButton(DialogDocument)
        self.pushButtonClose.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/close.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonClose.setIcon(icon7)
        self.pushButtonClose.setAutoDefault(False)
        self.pushButtonClose.setObjectName(_fromUtf8("pushButtonClose"))
        self.horizontalLayout.addWidget(self.pushButtonClose)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.labelMessage = QtGui.QLabel(DialogDocument)
        self.labelMessage.setText(_fromUtf8(""))
        self.labelMessage.setObjectName(_fromUtf8("labelMessage"))
        self.verticalLayout.addWidget(self.labelMessage)

        self.retranslateUi(DialogDocument)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DialogDocument)
        DialogDocument.setTabOrder(self.treeWidget, self.pushButtonSelect)
        DialogDocument.setTabOrder(self.pushButtonSelect, self.pushButtonAdd)
        DialogDocument.setTabOrder(self.pushButtonAdd, self.pushButtonEdit)
        DialogDocument.setTabOrder(self.pushButtonEdit, self.pushButtonDel)
        DialogDocument.setTabOrder(self.pushButtonDel, self.pushButtonSave)
        DialogDocument.setTabOrder(self.pushButtonSave, self.pushButtonRefresh)
        DialogDocument.setTabOrder(self.pushButtonRefresh, self.pushButtonClose)

    def retranslateUi(self, DialogDocument):
        DialogDocument.setWindowTitle(QtGui.QApplication.translate("DialogDocument", "Документ", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.setSortingEnabled(True)
        self.treeWidget.headerItem().setText(0, QtGui.QApplication.translate("DialogDocument", "Дата", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(1, QtGui.QApplication.translate("DialogDocument", "Номер", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(2, QtGui.QApplication.translate("DialogDocument", "Наименование", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DialogDocument", "<html><head/><body><p><span style=\" font-weight:600;\">Тип документа</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DialogDocument", "Наименование документа", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("DialogDocument", "Серия документа", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("DialogDocument", "<html><head/><body><p><span style=\" font-weight:600;\">Номер документа</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("DialogDocument", "Дата выдачи документа", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("DialogDocument", "Организация, выдавшая документ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("DialogDocument", "Номер документа в реестре", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditNumberReg.setWhatsThis(QtGui.QApplication.translate("DialogDocument", "Номер документа в реестре для регистрации нотариальных действий", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("DialogDocument", "Дата внесения сведений о документе", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("DialogDocument", "Дата начала действия", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("DialogDocument", "Дата прекращения действия", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("DialogDocument", "Кто удостоверил (ФИО нотариуса)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("DialogDocument", "Особые отметки", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("DialogDocument", "Код подразделения", None, QtGui.QApplication.UnicodeUTF8))
        self.dateEditDateReg.setWhatsThis(QtGui.QApplication.translate("DialogDocument", "Дата внесения сведений о документе в реестр для регистрации нотариальных действий", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("DialogDocument", "Создание", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("DialogDocument", "Дата", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageAttributes), QtGui.QApplication.translate("DialogDocument", "Атрибуты", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetAppliedFiles.headerItem().setText(0, QtGui.QApplication.translate("DialogDocument", "Вид файла", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetAppliedFiles.headerItem().setText(1, QtGui.QApplication.translate("DialogDocument", "Файл", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageAppliedFiles), QtGui.QApplication.translate("DialogDocument", "Приложенные файлы", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSelect.setToolTip(QtGui.QApplication.translate("DialogDocument", "Выбрать документ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAdd.setToolTip(QtGui.QApplication.translate("DialogDocument", "Добавить документ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonEdit.setToolTip(QtGui.QApplication.translate("DialogDocument", "Редактировать атрибуты документа", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDel.setToolTip(QtGui.QApplication.translate("DialogDocument", "Удалить документ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSave.setToolTip(QtGui.QApplication.translate("DialogDocument", "Сохранить атрибуты документа", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRefresh.setToolTip(QtGui.QApplication.translate("DialogDocument", "Обновить атрибуты документа", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonClose.setToolTip(QtGui.QApplication.translate("DialogDocument", "Закрыть окно", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
