# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'importxml.ui'
#
# Created: Mon Oct 28 11:22:27 2013
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ImportXMLDialog(object):
    def setupUi(self, ImportXMLDialog):
        ImportXMLDialog.setObjectName(_fromUtf8("ImportXMLDialog"))
        ImportXMLDialog.resize(640, 480)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ImportXMLDialog.sizePolicy().hasHeightForWidth())
        ImportXMLDialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/import_xml.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ImportXMLDialog.setWindowIcon(icon)
        ImportXMLDialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        ImportXMLDialog.setSizeGripEnabled(True)
        ImportXMLDialog.setModal(True)
        self.gridLayout_2 = QtGui.QGridLayout(ImportXMLDialog)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkBoxReverseXY = QtGui.QCheckBox(ImportXMLDialog)
        self.checkBoxReverseXY.setChecked(True)
        self.checkBoxReverseXY.setObjectName(_fromUtf8("checkBoxReverseXY"))
        self.gridLayout.addWidget(self.checkBoxReverseXY, 3, 1, 1, 1)
        self.lineEditFileXML = QtGui.QLineEdit(ImportXMLDialog)
        self.lineEditFileXML.setObjectName(_fromUtf8("lineEditFileXML"))
        self.gridLayout.addWidget(self.lineEditFileXML, 0, 1, 1, 1)
        self.pushButtonShowXML = QtGui.QPushButton(ImportXMLDialog)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/attributes.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonShowXML.setIcon(icon1)
        self.pushButtonShowXML.setObjectName(_fromUtf8("pushButtonShowXML"))
        self.gridLayout.addWidget(self.pushButtonShowXML, 1, 2, 1, 1)
        self.pushButtonCloseDialog = QtGui.QPushButton(ImportXMLDialog)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/close.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonCloseDialog.setIcon(icon2)
        self.pushButtonCloseDialog.setObjectName(_fromUtf8("pushButtonCloseDialog"))
        self.gridLayout.addWidget(self.pushButtonCloseDialog, 5, 2, 1, 1)
        self.progressBar = QtGui.QProgressBar(ImportXMLDialog)
        self.progressBar.setMinimum(0)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout.addWidget(self.progressBar, 5, 1, 1, 1)
        self.label_3 = QtGui.QLabel(ImportXMLDialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.listWidgetEvents = QtGui.QListWidget(ImportXMLDialog)
        self.listWidgetEvents.setObjectName(_fromUtf8("listWidgetEvents"))
        self.gridLayout.addWidget(self.listWidgetEvents, 2, 1, 1, 1)
        self.pushButtonFileXML = QtGui.QPushButton(ImportXMLDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonFileXML.sizePolicy().hasHeightForWidth())
        self.pushButtonFileXML.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/find_search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonFileXML.setIcon(icon3)
        self.pushButtonFileXML.setObjectName(_fromUtf8("pushButtonFileXML"))
        self.gridLayout.addWidget(self.pushButtonFileXML, 0, 2, 1, 1)
        self.pushButtonStartImport = QtGui.QPushButton(ImportXMLDialog)
        self.pushButtonStartImport.setIcon(icon)
        self.pushButtonStartImport.setObjectName(_fromUtf8("pushButtonStartImport"))
        self.gridLayout.addWidget(self.pushButtonStartImport, 2, 2, 1, 1)
        self.treeWidget = QtGui.QTreeWidget(ImportXMLDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.treeWidget.header().setDefaultSectionSize(250)
        self.gridLayout.addWidget(self.treeWidget, 1, 1, 1, 1)
        self.label = QtGui.QLabel(ImportXMLDialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.labelFileXML = QtGui.QLabel(ImportXMLDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelFileXML.sizePolicy().hasHeightForWidth())
        self.labelFileXML.setSizePolicy(sizePolicy)
        self.labelFileXML.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.labelFileXML.setObjectName(_fromUtf8("labelFileXML"))
        self.gridLayout.addWidget(self.labelFileXML, 0, 0, 1, 1)
        self.checkBoxNumGeopoint = QtGui.QCheckBox(ImportXMLDialog)
        self.checkBoxNumGeopoint.setChecked(True)
        self.checkBoxNumGeopoint.setObjectName(_fromUtf8("checkBoxNumGeopoint"))
        self.gridLayout.addWidget(self.checkBoxNumGeopoint, 4, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(ImportXMLDialog)
        QtCore.QMetaObject.connectSlotsByName(ImportXMLDialog)
        ImportXMLDialog.setTabOrder(self.lineEditFileXML, self.pushButtonFileXML)
        ImportXMLDialog.setTabOrder(self.pushButtonFileXML, self.treeWidget)
        ImportXMLDialog.setTabOrder(self.treeWidget, self.pushButtonShowXML)
        ImportXMLDialog.setTabOrder(self.pushButtonShowXML, self.listWidgetEvents)
        ImportXMLDialog.setTabOrder(self.listWidgetEvents, self.pushButtonStartImport)
        ImportXMLDialog.setTabOrder(self.pushButtonStartImport, self.checkBoxReverseXY)
        ImportXMLDialog.setTabOrder(self.checkBoxReverseXY, self.checkBoxNumGeopoint)
        ImportXMLDialog.setTabOrder(self.checkBoxNumGeopoint, self.pushButtonCloseDialog)

    def retranslateUi(self, ImportXMLDialog):
        ImportXMLDialog.setWindowTitle(QtGui.QApplication.translate("ImportXMLDialog", "Импорт XML", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxReverseXY.setText(QtGui.QApplication.translate("ImportXMLDialog", "Менять местами координаты X, Y (переходить от геодезических к ГИС)", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonShowXML.setText(QtGui.QApplication.translate("ImportXMLDialog", "Просмотр XML", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCloseDialog.setText(QtGui.QApplication.translate("ImportXMLDialog", "Закрыть", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ImportXMLDialog", "<html><head/><body><p align=\"right\">Выполнение<br/>операций</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonFileXML.setText(QtGui.QApplication.translate("ImportXMLDialog", "Выбрать...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonStartImport.setText(QtGui.QApplication.translate("ImportXMLDialog", "Импорт XML", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(0, QtGui.QApplication.translate("ImportXMLDialog", "Тэг", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(1, QtGui.QApplication.translate("ImportXMLDialog", "Атрибут", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ImportXMLDialog", "<html><head/><body><p align=\"right\">Содержимое</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFileXML.setText(QtGui.QApplication.translate("ImportXMLDialog", "<html><head/><body><p align=\"right\">Файл XML</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxNumGeopoint.setText(QtGui.QApplication.translate("ImportXMLDialog", "Импортировать номер точки из атрибута Num_Geopoint", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
