# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kn.ui'
#
# Created: Mon Oct 28 11:22:32 2013
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_DialogKn(object):
    def setupUi(self, DialogKn):
        DialogKn.setObjectName(_fromUtf8("DialogKn"))
        DialogKn.resize(460, 280)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/kn.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogKn.setWindowIcon(icon)
        DialogKn.setSizeGripEnabled(True)
        DialogKn.setModal(True)
        self.gridLayout = QtGui.QGridLayout(DialogKn)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lineEditDefinition = QtGui.QLineEdit(DialogKn)
        self.lineEditDefinition.setEnabled(False)
        self.lineEditDefinition.setObjectName(_fromUtf8("lineEditDefinition"))
        self.gridLayout_2.addWidget(self.lineEditDefinition, 1, 1, 1, 1)
        self.lineEditOther = QtGui.QLineEdit(DialogKn)
        self.lineEditOther.setEnabled(False)
        self.lineEditOther.setObjectName(_fromUtf8("lineEditOther"))
        self.gridLayout_2.addWidget(self.lineEditOther, 2, 1, 1, 1)
        self.label_2 = QtGui.QLabel(DialogKn)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_3 = QtGui.QLabel(DialogKn)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 1)
        self.label = QtGui.QLabel(DialogKn)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.lineEditKn = QtGui.QLineEdit(DialogKn)
        self.lineEditKn.setEnabled(False)
        self.lineEditKn.setMaxLength(40)
        self.lineEditKn.setObjectName(_fromUtf8("lineEditKn"))
        self.gridLayout_2.addWidget(self.lineEditKn, 0, 1, 1, 1)
        self.treeWidget = QtGui.QTreeWidget(DialogKn)
        self.treeWidget.setEnabled(False)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.gridLayout_2.addWidget(self.treeWidget, 3, 1, 1, 1)
        self.label_4 = QtGui.QLabel(DialogKn)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(DialogKn)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.lineEditNumber = QtGui.QLineEdit(DialogKn)
        self.lineEditNumber.setEnabled(False)
        self.lineEditNumber.setObjectName(_fromUtf8("lineEditNumber"))
        self.gridLayout_2.addWidget(self.lineEditNumber, 4, 1, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pushButtonAddDocument = QtGui.QPushButton(DialogKn)
        self.pushButtonAddDocument.setEnabled(False)
        self.pushButtonAddDocument.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/symbol_add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonAddDocument.setIcon(icon1)
        self.pushButtonAddDocument.setObjectName(_fromUtf8("pushButtonAddDocument"))
        self.verticalLayout.addWidget(self.pushButtonAddDocument)
        self.pushButtonEditDocument = QtGui.QPushButton(DialogKn)
        self.pushButtonEditDocument.setEnabled(False)
        self.pushButtonEditDocument.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/edit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonEditDocument.setIcon(icon2)
        self.pushButtonEditDocument.setObjectName(_fromUtf8("pushButtonEditDocument"))
        self.verticalLayout.addWidget(self.pushButtonEditDocument)
        self.pushButtonDelDocument = QtGui.QPushButton(DialogKn)
        self.pushButtonDelDocument.setEnabled(False)
        self.pushButtonDelDocument.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/symbol_remove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonDelDocument.setIcon(icon3)
        self.pushButtonDelDocument.setObjectName(_fromUtf8("pushButtonDelDocument"))
        self.verticalLayout.addWidget(self.pushButtonDelDocument)
        self.gridLayout_2.addLayout(self.verticalLayout, 3, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButtonSave = QtGui.QPushButton(DialogKn)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonSave.setIcon(icon4)
        self.pushButtonSave.setDefault(True)
        self.pushButtonSave.setObjectName(_fromUtf8("pushButtonSave"))
        self.horizontalLayout.addWidget(self.pushButtonSave)
        self.pushButtonClose = QtGui.QPushButton(DialogKn)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/close.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonClose.setIcon(icon5)
        self.pushButtonClose.setObjectName(_fromUtf8("pushButtonClose"))
        self.horizontalLayout.addWidget(self.pushButtonClose)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(DialogKn)
        QtCore.QObject.connect(self.treeWidget, QtCore.SIGNAL(_fromUtf8("doubleClicked(QModelIndex)")), self.pushButtonEditDocument.click)
        QtCore.QMetaObject.connectSlotsByName(DialogKn)
        DialogKn.setTabOrder(self.lineEditKn, self.lineEditDefinition)
        DialogKn.setTabOrder(self.lineEditDefinition, self.lineEditOther)
        DialogKn.setTabOrder(self.lineEditOther, self.treeWidget)
        DialogKn.setTabOrder(self.treeWidget, self.pushButtonAddDocument)
        DialogKn.setTabOrder(self.pushButtonAddDocument, self.pushButtonEditDocument)
        DialogKn.setTabOrder(self.pushButtonEditDocument, self.pushButtonDelDocument)
        DialogKn.setTabOrder(self.pushButtonDelDocument, self.lineEditNumber)
        DialogKn.setTabOrder(self.lineEditNumber, self.pushButtonSave)
        DialogKn.setTabOrder(self.pushButtonSave, self.pushButtonClose)

    def retranslateUi(self, DialogKn):
        DialogKn.setWindowTitle(QtGui.QApplication.translate("DialogKn", "Кадастровый номер", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DialogKn", "<html><head/><body><p align=\"right\">Иное (земли общего<br/>пользования)</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("DialogKn", "<html><head/><body><p align=\"right\">Документы</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DialogKn", "<html><head/><body><p align=\"right\">Обозначение ЗУ</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.setSortingEnabled(True)
        self.treeWidget.headerItem().setText(0, QtGui.QApplication.translate("DialogKn", "Номер", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(1, QtGui.QApplication.translate("DialogKn", "Наменование", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("DialogKn", "<html><head/><body><p align=\"right\">Кадастровый <br/>номер</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("DialogKn", "<html><head/><body><p align=\"right\">Иной номер<br/>(ОКС)</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSave.setText(QtGui.QApplication.translate("DialogKn", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonClose.setText(QtGui.QApplication.translate("DialogKn", "Отмена", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
