# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'meanssurvey.ui'
#
# Created: Mon Oct 28 11:22:33 2013
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_DialogMeansSurvey(object):
    def setupUi(self, DialogMeansSurvey):
        DialogMeansSurvey.setObjectName(_fromUtf8("DialogMeansSurvey"))
        DialogMeansSurvey.resize(640, 380)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/taheo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogMeansSurvey.setWindowIcon(icon)
        DialogMeansSurvey.setSizeGripEnabled(True)
        DialogMeansSurvey.setModal(True)
        self.verticalLayout = QtGui.QVBoxLayout(DialogMeansSurvey)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.treeWidget = QtGui.QTreeWidget(DialogMeansSurvey)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.verticalLayout.addWidget(self.treeWidget)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(DialogMeansSurvey)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.lineEditName = QtGui.QLineEdit(DialogMeansSurvey)
        self.lineEditName.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditName.setInputMask(_fromUtf8(""))
        self.lineEditName.setObjectName(_fromUtf8("lineEditName"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditName)
        self.label_2 = QtGui.QLabel(DialogMeansSurvey)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.lineEditCertificate = QtGui.QLineEdit(DialogMeansSurvey)
        self.lineEditCertificate.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditCertificate.setObjectName(_fromUtf8("lineEditCertificate"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditCertificate)
        self.label_3 = QtGui.QLabel(DialogMeansSurvey)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.lineEditCertificateVerification = QtGui.QLineEdit(DialogMeansSurvey)
        self.lineEditCertificateVerification.setInputMask(_fromUtf8(""))
        self.lineEditCertificateVerification.setObjectName(_fromUtf8("lineEditCertificateVerification"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditCertificateVerification)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButtonSelect = QtGui.QPushButton(DialogMeansSurvey)
        self.pushButtonSelect.setEnabled(False)
        self.pushButtonSelect.setStatusTip(_fromUtf8(""))
        self.pushButtonSelect.setWhatsThis(_fromUtf8(""))
        self.pushButtonSelect.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/symbol_check.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonSelect.setIcon(icon1)
        self.pushButtonSelect.setAutoDefault(False)
        self.pushButtonSelect.setDefault(True)
        self.pushButtonSelect.setObjectName(_fromUtf8("pushButtonSelect"))
        self.horizontalLayout.addWidget(self.pushButtonSelect)
        self.pushButtonAdd = QtGui.QPushButton(DialogMeansSurvey)
        self.pushButtonAdd.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/symbol_add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonAdd.setIcon(icon2)
        self.pushButtonAdd.setAutoDefault(False)
        self.pushButtonAdd.setObjectName(_fromUtf8("pushButtonAdd"))
        self.horizontalLayout.addWidget(self.pushButtonAdd)
        self.pushButtonEdit = QtGui.QPushButton(DialogMeansSurvey)
        self.pushButtonEdit.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/edit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonEdit.setIcon(icon3)
        self.pushButtonEdit.setAutoDefault(False)
        self.pushButtonEdit.setObjectName(_fromUtf8("pushButtonEdit"))
        self.horizontalLayout.addWidget(self.pushButtonEdit)
        self.pushButtonDel = QtGui.QPushButton(DialogMeansSurvey)
        self.pushButtonDel.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/symbol_remove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonDel.setIcon(icon4)
        self.pushButtonDel.setAutoDefault(False)
        self.pushButtonDel.setObjectName(_fromUtf8("pushButtonDel"))
        self.horizontalLayout.addWidget(self.pushButtonDel)
        self.pushButtonSave = QtGui.QPushButton(DialogMeansSurvey)
        self.pushButtonSave.setEnabled(False)
        self.pushButtonSave.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonSave.setIcon(icon5)
        self.pushButtonSave.setAutoDefault(False)
        self.pushButtonSave.setObjectName(_fromUtf8("pushButtonSave"))
        self.horizontalLayout.addWidget(self.pushButtonSave)
        self.pushButtonRefresh = QtGui.QPushButton(DialogMeansSurvey)
        self.pushButtonRefresh.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonRefresh.setIcon(icon6)
        self.pushButtonRefresh.setAutoDefault(False)
        self.pushButtonRefresh.setObjectName(_fromUtf8("pushButtonRefresh"))
        self.horizontalLayout.addWidget(self.pushButtonRefresh)
        self.pushButtonClose = QtGui.QPushButton(DialogMeansSurvey)
        self.pushButtonClose.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/close.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonClose.setIcon(icon7)
        self.pushButtonClose.setAutoDefault(False)
        self.pushButtonClose.setObjectName(_fromUtf8("pushButtonClose"))
        self.horizontalLayout.addWidget(self.pushButtonClose)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.labelMessage = QtGui.QLabel(DialogMeansSurvey)
        self.labelMessage.setText(_fromUtf8(""))
        self.labelMessage.setObjectName(_fromUtf8("labelMessage"))
        self.verticalLayout.addWidget(self.labelMessage)

        self.retranslateUi(DialogMeansSurvey)
        QtCore.QMetaObject.connectSlotsByName(DialogMeansSurvey)
        DialogMeansSurvey.setTabOrder(self.treeWidget, self.lineEditName)
        DialogMeansSurvey.setTabOrder(self.lineEditName, self.lineEditCertificate)
        DialogMeansSurvey.setTabOrder(self.lineEditCertificate, self.lineEditCertificateVerification)
        DialogMeansSurvey.setTabOrder(self.lineEditCertificateVerification, self.pushButtonSelect)
        DialogMeansSurvey.setTabOrder(self.pushButtonSelect, self.pushButtonAdd)
        DialogMeansSurvey.setTabOrder(self.pushButtonAdd, self.pushButtonEdit)
        DialogMeansSurvey.setTabOrder(self.pushButtonEdit, self.pushButtonDel)
        DialogMeansSurvey.setTabOrder(self.pushButtonDel, self.pushButtonSave)
        DialogMeansSurvey.setTabOrder(self.pushButtonSave, self.pushButtonRefresh)
        DialogMeansSurvey.setTabOrder(self.pushButtonRefresh, self.pushButtonClose)

    def retranslateUi(self, DialogMeansSurvey):
        DialogMeansSurvey.setWindowTitle(QtGui.QApplication.translate("DialogMeansSurvey", "Средства измерения", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.setSortingEnabled(True)
        self.treeWidget.headerItem().setText(0, QtGui.QApplication.translate("DialogMeansSurvey", "Название", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DialogMeansSurvey", "Название прибора ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DialogMeansSurvey", "Реквизиты сертификата<br />прибора", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("DialogMeansSurvey", "Реквизиты свидетельства<br />о поверке прибора ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSelect.setToolTip(QtGui.QApplication.translate("DialogMeansSurvey", "Выбрать прибор", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAdd.setToolTip(QtGui.QApplication.translate("DialogMeansSurvey", "Добавить прибор", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonEdit.setToolTip(QtGui.QApplication.translate("DialogMeansSurvey", "Редактировать атрибуты прибора", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDel.setToolTip(QtGui.QApplication.translate("DialogMeansSurvey", "Удалить прибор", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSave.setToolTip(QtGui.QApplication.translate("DialogMeansSurvey", "Сохранить атрибуты прибора", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRefresh.setToolTip(QtGui.QApplication.translate("DialogMeansSurvey", "Обновить атрибуты прибора", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonClose.setToolTip(QtGui.QApplication.translate("DialogMeansSurvey", "Закрыть окно", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
