# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mp.ui'
#
# Created: Mon Oct 28 11:22:34 2013
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_DialogMP(object):
    def setupUi(self, DialogMP):
        DialogMP.setObjectName(_fromUtf8("DialogMP"))
        DialogMP.resize(801, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/mp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogMP.setWindowIcon(icon)
        DialogMP.setSizeGripEnabled(True)
        self.verticalLayout_2 = QtGui.QVBoxLayout(DialogMP)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.comboBoxMp = QtGui.QComboBox(DialogMP)
        self.comboBoxMp.setObjectName(_fromUtf8("comboBoxMp"))
        self.verticalLayout.addWidget(self.comboBoxMp)
        self.treeWidget = QtGui.QTreeWidget(DialogMP)
        self.treeWidget.setToolTip(_fromUtf8(""))
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.verticalLayout.addWidget(self.treeWidget)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tabWidget = QtGui.QTabWidget(DialogMP)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabEDocument = QtGui.QWidget()
        self.tabEDocument.setEnabled(True)
        self.tabEDocument.setObjectName(_fromUtf8("tabEDocument"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabEDocument)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_21 = QtGui.QLabel(self.tabEDocument)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_2.addWidget(self.label_21, 5, 0, 1, 1)
        self.lineEditCreateDate = QtGui.QLineEdit(self.tabEDocument)
        self.lineEditCreateDate.setReadOnly(True)
        self.lineEditCreateDate.setObjectName(_fromUtf8("lineEditCreateDate"))
        self.gridLayout_2.addWidget(self.lineEditCreateDate, 5, 1, 1, 1)
        self.lineEditCreateUser = QtGui.QLineEdit(self.tabEDocument)
        self.lineEditCreateUser.setReadOnly(True)
        self.lineEditCreateUser.setObjectName(_fromUtf8("lineEditCreateUser"))
        self.gridLayout_2.addWidget(self.lineEditCreateUser, 4, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.tabEDocument)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.comboBoxEDocCodeType = QtGui.QComboBox(self.tabEDocument)
        self.comboBoxEDocCodeType.setObjectName(_fromUtf8("comboBoxEDocCodeType"))
        self.gridLayout_2.addWidget(self.comboBoxEDocCodeType, 0, 1, 1, 1)
        self.spinBoxShemaVersion = QtGui.QSpinBox(self.tabEDocument)
        self.spinBoxShemaVersion.setMinimum(4)
        self.spinBoxShemaVersion.setMaximum(4)
        self.spinBoxShemaVersion.setObjectName(_fromUtf8("spinBoxShemaVersion"))
        self.gridLayout_2.addWidget(self.spinBoxShemaVersion, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.tabEDocument)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.tabEDocument)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.lineEditMpGUID = QtGui.QLineEdit(self.tabEDocument)
        self.lineEditMpGUID.setReadOnly(True)
        self.lineEditMpGUID.setObjectName(_fromUtf8("lineEditMpGUID"))
        self.gridLayout_2.addWidget(self.lineEditMpGUID, 2, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.tabEDocument)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_2.addWidget(self.label_20, 4, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tabEDocument, _fromUtf8(""))
        self.tabTitle = QtGui.QWidget()
        self.tabTitle.setObjectName(_fromUtf8("tabTitle"))
        self.gridLayout = QtGui.QGridLayout(self.tabTitle)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButtonEditContractor = QtGui.QPushButton(self.tabTitle)
        self.pushButtonEditContractor.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/edit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonEditContractor.setIcon(icon1)
        self.pushButtonEditContractor.setAutoDefault(False)
        self.pushButtonEditContractor.setObjectName(_fromUtf8("pushButtonEditContractor"))
        self.gridLayout.addWidget(self.pushButtonEditContractor, 1, 2, 1, 1)
        self.textEditReason = QtGui.QTextEdit(self.tabTitle)
        self.textEditReason.setObjectName(_fromUtf8("textEditReason"))
        self.gridLayout.addWidget(self.textEditReason, 3, 1, 1, 1)
        self.textEditPurpose = QtGui.QTextEdit(self.tabTitle)
        self.textEditPurpose.setObjectName(_fromUtf8("textEditPurpose"))
        self.gridLayout.addWidget(self.textEditPurpose, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.tabTitle)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.tabTitle)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.comboBoxContractor = QtGui.QComboBox(self.tabTitle)
        self.comboBoxContractor.setEditable(False)
        self.comboBoxContractor.setObjectName(_fromUtf8("comboBoxContractor"))
        self.gridLayout.addWidget(self.comboBoxContractor, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.tabTitle)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.dateEditDateWork = QtGui.QDateEdit(self.tabTitle)
        self.dateEditDateWork.setCalendarPopup(True)
        self.dateEditDateWork.setObjectName(_fromUtf8("dateEditDateWork"))
        self.gridLayout.addWidget(self.dateEditDateWork, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.tabTitle)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButtonPurpose = QtGui.QPushButton(self.tabTitle)
        self.pushButtonPurpose.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/format_indent_more.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonPurpose.setIcon(icon2)
        self.pushButtonPurpose.setAutoDefault(False)
        self.pushButtonPurpose.setObjectName(_fromUtf8("pushButtonPurpose"))
        self.gridLayout.addWidget(self.pushButtonPurpose, 2, 2, 1, 1)
        self.pushButtonReason = QtGui.QPushButton(self.tabTitle)
        self.pushButtonReason.setText(_fromUtf8(""))
        self.pushButtonReason.setIcon(icon2)
        self.pushButtonReason.setAutoDefault(False)
        self.pushButtonReason.setObjectName(_fromUtf8("pushButtonReason"))
        self.gridLayout.addWidget(self.pushButtonReason, 3, 2, 1, 1)
        self.comboBoxClient = QtGui.QComboBox(self.tabTitle)
        self.comboBoxClient.setObjectName(_fromUtf8("comboBoxClient"))
        self.gridLayout.addWidget(self.comboBoxClient, 4, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.tabTitle)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 4, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.tabTitle)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 5, 0, 1, 1)
        self.dateEditAcceptWork = QtGui.QDateEdit(self.tabTitle)
        self.dateEditAcceptWork.setCalendarPopup(True)
        self.dateEditAcceptWork.setObjectName(_fromUtf8("dateEditAcceptWork"))
        self.gridLayout.addWidget(self.dateEditAcceptWork, 5, 1, 1, 1)
        self.pushButtonEditClient = QtGui.QPushButton(self.tabTitle)
        self.pushButtonEditClient.setText(_fromUtf8(""))
        self.pushButtonEditClient.setIcon(icon1)
        self.pushButtonEditClient.setAutoDefault(False)
        self.pushButtonEditClient.setObjectName(_fromUtf8("pushButtonEditClient"))
        self.gridLayout.addWidget(self.pushButtonEditClient, 4, 2, 1, 1)
        self.tabWidget.addTab(self.tabTitle, _fromUtf8(""))
        self.tabPackage = QtGui.QWidget()
        self.tabPackage.setObjectName(_fromUtf8("tabPackage"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabPackage)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.treeWidgetParcel = QtGui.QTreeWidget(self.tabPackage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidgetParcel.sizePolicy().hasHeightForWidth())
        self.treeWidgetParcel.setSizePolicy(sizePolicy)
        self.treeWidgetParcel.setObjectName(_fromUtf8("treeWidgetParcel"))
        self.gridLayout_3.addWidget(self.treeWidgetParcel, 0, 1, 1, 1)
        self.labelParcel = QtGui.QLabel(self.tabPackage)
        self.labelParcel.setObjectName(_fromUtf8("labelParcel"))
        self.gridLayout_3.addWidget(self.labelParcel, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabPackage, _fromUtf8(""))
        self.tabCoordSystems = QtGui.QWidget()
        self.tabCoordSystems.setObjectName(_fromUtf8("tabCoordSystems"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.tabCoordSystems)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_18 = QtGui.QLabel(self.tabCoordSystems)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_10.addWidget(self.label_18)
        self.treeWidgetCoordSystems = QtGui.QTreeWidget(self.tabCoordSystems)
        self.treeWidgetCoordSystems.setObjectName(_fromUtf8("treeWidgetCoordSystems"))
        self.horizontalLayout_10.addWidget(self.treeWidgetCoordSystems)
        self.tabWidget.addTab(self.tabCoordSystems, _fromUtf8(""))
        self.tabInputData = QtGui.QWidget()
        self.tabInputData.setObjectName(_fromUtf8("tabInputData"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tabInputData)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.toolBox = QtGui.QToolBox(self.tabInputData)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.pageDocument = QtGui.QWidget()
        self.pageDocument.setGeometry(QtCore.QRect(0, 0, 96, 79))
        self.pageDocument.setObjectName(_fromUtf8("pageDocument"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.pageDocument)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.treeWidgetDocument = QtGui.QTreeWidget(self.pageDocument)
        self.treeWidgetDocument.setObjectName(_fromUtf8("treeWidgetDocument"))
        self.verticalLayout_7.addWidget(self.treeWidgetDocument)
        self.toolBox.addItem(self.pageDocument, _fromUtf8(""))
        self.pageGeodesicBase = QtGui.QWidget()
        self.pageGeodesicBase.setGeometry(QtCore.QRect(0, 0, 96, 79))
        self.pageGeodesicBase.setObjectName(_fromUtf8("pageGeodesicBase"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.pageGeodesicBase)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.treeWidgetGeodesicBase = QtGui.QTreeWidget(self.pageGeodesicBase)
        self.treeWidgetGeodesicBase.setObjectName(_fromUtf8("treeWidgetGeodesicBase"))
        self.verticalLayout_8.addWidget(self.treeWidgetGeodesicBase)
        self.toolBox.addItem(self.pageGeodesicBase, _fromUtf8(""))
        self.pageMeansSurvey = QtGui.QWidget()
        self.pageMeansSurvey.setGeometry(QtCore.QRect(0, 0, 96, 79))
        self.pageMeansSurvey.setObjectName(_fromUtf8("pageMeansSurvey"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.pageMeansSurvey)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.treeWidgetMeansSurvey = QtGui.QTreeWidget(self.pageMeansSurvey)
        self.treeWidgetMeansSurvey.setObjectName(_fromUtf8("treeWidgetMeansSurvey"))
        self.verticalLayout_9.addWidget(self.treeWidgetMeansSurvey)
        self.toolBox.addItem(self.pageMeansSurvey, _fromUtf8(""))
        self.pageRealty = QtGui.QWidget()
        self.pageRealty.setGeometry(QtCore.QRect(0, 0, 96, 79))
        self.pageRealty.setObjectName(_fromUtf8("pageRealty"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.pageRealty)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.treeWidgetRealty = QtGui.QTreeWidget(self.pageRealty)
        self.treeWidgetRealty.setObjectName(_fromUtf8("treeWidgetRealty"))
        self.verticalLayout_10.addWidget(self.treeWidgetRealty)
        self.toolBox.addItem(self.pageRealty, _fromUtf8(""))
        self.pageSubParcel = QtGui.QWidget()
        self.pageSubParcel.setGeometry(QtCore.QRect(0, 0, 96, 79))
        self.pageSubParcel.setObjectName(_fromUtf8("pageSubParcel"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.pageSubParcel)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.treeWidgetSubParcel = QtGui.QTreeWidget(self.pageSubParcel)
        self.treeWidgetSubParcel.setObjectName(_fromUtf8("treeWidgetSubParcel"))
        self.verticalLayout_11.addWidget(self.treeWidgetSubParcel)
        self.toolBox.addItem(self.pageSubParcel, _fromUtf8(""))
        self.verticalLayout_6.addWidget(self.toolBox)
        self.tabWidget.addTab(self.tabInputData, _fromUtf8(""))
        self.tabSurvey = QtGui.QWidget()
        self.tabSurvey.setObjectName(_fromUtf8("tabSurvey"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.tabSurvey)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_14 = QtGui.QLabel(self.tabSurvey)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_6.addWidget(self.label_14)
        self.treeWidgetSurvey = QtGui.QTreeWidget(self.tabSurvey)
        self.treeWidgetSurvey.setObjectName(_fromUtf8("treeWidgetSurvey"))
        self.horizontalLayout_6.addWidget(self.treeWidgetSurvey)
        self.tabWidget.addTab(self.tabSurvey, _fromUtf8(""))
        self.tabConclusion = QtGui.QWidget()
        self.tabConclusion.setObjectName(_fromUtf8("tabConclusion"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabConclusion)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.textEditConclusion = QtGui.QTextEdit(self.tabConclusion)
        self.textEditConclusion.setObjectName(_fromUtf8("textEditConclusion"))
        self.verticalLayout_5.addWidget(self.textEditConclusion)
        self.pushButtonConclusion = QtGui.QPushButton(self.tabConclusion)
        self.pushButtonConclusion.setText(_fromUtf8(""))
        self.pushButtonConclusion.setIcon(icon2)
        self.pushButtonConclusion.setAutoDefault(False)
        self.pushButtonConclusion.setObjectName(_fromUtf8("pushButtonConclusion"))
        self.verticalLayout_5.addWidget(self.pushButtonConclusion)
        self.tabWidget.addTab(self.tabConclusion, _fromUtf8(""))
        self.tabSchemeGeodesicPlotting = QtGui.QWidget()
        self.tabSchemeGeodesicPlotting.setObjectName(_fromUtf8("tabSchemeGeodesicPlotting"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.tabSchemeGeodesicPlotting)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_15 = QtGui.QLabel(self.tabSchemeGeodesicPlotting)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_7.addWidget(self.label_15)
        self.treeWidgetSchemeGeodesicPlotting = QtGui.QTreeWidget(self.tabSchemeGeodesicPlotting)
        self.treeWidgetSchemeGeodesicPlotting.setObjectName(_fromUtf8("treeWidgetSchemeGeodesicPlotting"))
        self.horizontalLayout_7.addWidget(self.treeWidgetSchemeGeodesicPlotting)
        self.tabWidget.addTab(self.tabSchemeGeodesicPlotting, _fromUtf8(""))
        self.tabDispositionParcels = QtGui.QWidget()
        self.tabDispositionParcels.setObjectName(_fromUtf8("tabDispositionParcels"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tabDispositionParcels)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_12 = QtGui.QLabel(self.tabDispositionParcels)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_4.addWidget(self.label_12)
        self.treeWidgetSchemeDispositionParcels = QtGui.QTreeWidget(self.tabDispositionParcels)
        self.treeWidgetSchemeDispositionParcels.setObjectName(_fromUtf8("treeWidgetSchemeDispositionParcels"))
        self.horizontalLayout_4.addWidget(self.treeWidgetSchemeDispositionParcels)
        self.tabWidget.addTab(self.tabDispositionParcels, _fromUtf8(""))
        self.tabDiagramParcels = QtGui.QWidget()
        self.tabDiagramParcels.setObjectName(_fromUtf8("tabDiagramParcels"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.tabDiagramParcels)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_13 = QtGui.QLabel(self.tabDiagramParcels)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_5.addWidget(self.label_13)
        self.treeWidgetDiagramParcels = QtGui.QTreeWidget(self.tabDiagramParcels)
        self.treeWidgetDiagramParcels.setObjectName(_fromUtf8("treeWidgetDiagramParcels"))
        self.horizontalLayout_5.addWidget(self.treeWidgetDiagramParcels)
        self.tabWidget.addTab(self.tabDiagramParcels, _fromUtf8(""))
        self.tabAgreementDocument = QtGui.QWidget()
        self.tabAgreementDocument.setObjectName(_fromUtf8("tabAgreementDocument"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.tabAgreementDocument)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_16 = QtGui.QLabel(self.tabAgreementDocument)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_8.addWidget(self.label_16)
        self.treeWidgetAgreementDocument = QtGui.QTreeWidget(self.tabAgreementDocument)
        self.treeWidgetAgreementDocument.setObjectName(_fromUtf8("treeWidgetAgreementDocument"))
        self.horizontalLayout_8.addWidget(self.treeWidgetAgreementDocument)
        self.tabWidget.addTab(self.tabAgreementDocument, _fromUtf8(""))
        self.tabNodalPointSchemes = QtGui.QWidget()
        self.tabNodalPointSchemes.setObjectName(_fromUtf8("tabNodalPointSchemes"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.tabNodalPointSchemes)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_17 = QtGui.QLabel(self.tabNodalPointSchemes)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_9.addWidget(self.label_17)
        self.treeWidgetNodalPointSchemes = QtGui.QTreeWidget(self.tabNodalPointSchemes)
        self.treeWidgetNodalPointSchemes.setObjectName(_fromUtf8("treeWidgetNodalPointSchemes"))
        self.horizontalLayout_9.addWidget(self.treeWidgetNodalPointSchemes)
        self.tabWidget.addTab(self.tabNodalPointSchemes, _fromUtf8(""))
        self.tabAppendix = QtGui.QWidget()
        self.tabAppendix.setObjectName(_fromUtf8("tabAppendix"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.tabAppendix)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_19 = QtGui.QLabel(self.tabAppendix)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_11.addWidget(self.label_19)
        self.treeWidgetAppendix = QtGui.QTreeWidget(self.tabAppendix)
        self.treeWidgetAppendix.setObjectName(_fromUtf8("treeWidgetAppendix"))
        self.horizontalLayout_11.addWidget(self.treeWidgetAppendix)
        self.tabWidget.addTab(self.tabAppendix, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButtonAddSectionMp = QtGui.QPushButton(DialogMP)
        self.pushButtonAddSectionMp.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/symbol_add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonAddSectionMp.setIcon(icon3)
        self.pushButtonAddSectionMp.setAutoDefault(False)
        self.pushButtonAddSectionMp.setObjectName(_fromUtf8("pushButtonAddSectionMp"))
        self.horizontalLayout_3.addWidget(self.pushButtonAddSectionMp)
        self.pushButtonSaveData = QtGui.QPushButton(DialogMP)
        self.pushButtonSaveData.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonSaveData.setIcon(icon4)
        self.pushButtonSaveData.setAutoDefault(False)
        self.pushButtonSaveData.setObjectName(_fromUtf8("pushButtonSaveData"))
        self.horizontalLayout_3.addWidget(self.pushButtonSaveData)
        self.pushButtonEditData = QtGui.QPushButton(DialogMP)
        self.pushButtonEditData.setEnabled(False)
        self.pushButtonEditData.setIcon(icon1)
        self.pushButtonEditData.setAutoDefault(False)
        self.pushButtonEditData.setObjectName(_fromUtf8("pushButtonEditData"))
        self.horizontalLayout_3.addWidget(self.pushButtonEditData)
        self.pushButtonDeleteSectionMp = QtGui.QPushButton(DialogMP)
        self.pushButtonDeleteSectionMp.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/symbol_remove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonDeleteSectionMp.setIcon(icon5)
        self.pushButtonDeleteSectionMp.setAutoDefault(False)
        self.pushButtonDeleteSectionMp.setObjectName(_fromUtf8("pushButtonDeleteSectionMp"))
        self.horizontalLayout_3.addWidget(self.pushButtonDeleteSectionMp)
        self.pushButtonRefreshData = QtGui.QPushButton(DialogMP)
        self.pushButtonRefreshData.setEnabled(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonRefreshData.setIcon(icon6)
        self.pushButtonRefreshData.setAutoDefault(False)
        self.pushButtonRefreshData.setObjectName(_fromUtf8("pushButtonRefreshData"))
        self.horizontalLayout_3.addWidget(self.pushButtonRefreshData)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButtonCreateNewMp = QtGui.QPushButton(DialogMP)
        self.pushButtonCreateNewMp.setIcon(icon)
        self.pushButtonCreateNewMp.setAutoDefault(False)
        self.pushButtonCreateNewMp.setObjectName(_fromUtf8("pushButtonCreateNewMp"))
        self.horizontalLayout.addWidget(self.pushButtonCreateNewMp)
        self.pushButtonDeleteMp = QtGui.QPushButton(DialogMP)
        self.pushButtonDeleteMp.setEnabled(False)
        self.pushButtonDeleteMp.setIcon(icon)
        self.pushButtonDeleteMp.setAutoDefault(False)
        self.pushButtonDeleteMp.setObjectName(_fromUtf8("pushButtonDeleteMp"))
        self.horizontalLayout.addWidget(self.pushButtonDeleteMp)
        self.pushButtonCreateXML = QtGui.QPushButton(DialogMP)
        self.pushButtonCreateXML.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/export_xml.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonCreateXML.setIcon(icon7)
        self.pushButtonCreateXML.setAutoDefault(False)
        self.pushButtonCreateXML.setObjectName(_fromUtf8("pushButtonCreateXML"))
        self.horizontalLayout.addWidget(self.pushButtonCreateXML)
        self.label_6 = QtGui.QLabel(DialogMP)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout.addWidget(self.label_6)
        self.lineEditFind = QtGui.QLineEdit(DialogMP)
        self.lineEditFind.setText(_fromUtf8(""))
        self.lineEditFind.setObjectName(_fromUtf8("lineEditFind"))
        self.horizontalLayout.addWidget(self.lineEditFind)
        self.label_7 = QtGui.QLabel(DialogMP)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout.addWidget(self.label_7)
        self.comboBoxFindField = QtGui.QComboBox(DialogMP)
        self.comboBoxFindField.setObjectName(_fromUtf8("comboBoxFindField"))
        self.comboBoxFindField.addItem(_fromUtf8(""))
        self.comboBoxFindField.addItem(_fromUtf8(""))
        self.comboBoxFindField.addItem(_fromUtf8(""))
        self.comboBoxFindField.addItem(_fromUtf8(""))
        self.comboBoxFindField.addItem(_fromUtf8(""))
        self.comboBoxFindField.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboBoxFindField)
        self.pushButtonFindMp = QtGui.QPushButton(DialogMP)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/find_search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonFindMp.setIcon(icon8)
        self.pushButtonFindMp.setDefault(True)
        self.pushButtonFindMp.setObjectName(_fromUtf8("pushButtonFindMp"))
        self.horizontalLayout.addWidget(self.pushButtonFindMp)
        self.pushButtonCloseDialog = QtGui.QPushButton(DialogMP)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/close.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonCloseDialog.setIcon(icon9)
        self.pushButtonCloseDialog.setAutoDefault(False)
        self.pushButtonCloseDialog.setObjectName(_fromUtf8("pushButtonCloseDialog"))
        self.horizontalLayout.addWidget(self.pushButtonCloseDialog)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.labelMessage = QtGui.QLabel(DialogMP)
        self.labelMessage.setText(_fromUtf8(""))
        self.labelMessage.setObjectName(_fromUtf8("labelMessage"))
        self.verticalLayout_2.addWidget(self.labelMessage)

        self.retranslateUi(DialogMP)
        self.tabWidget.setCurrentIndex(1)
        self.toolBox.setCurrentIndex(0)
        QtCore.QObject.connect(self.treeWidgetAppendix, QtCore.SIGNAL(_fromUtf8("doubleClicked(QModelIndex)")), self.pushButtonEditData.click)
        QtCore.QObject.connect(self.treeWidgetDocument, QtCore.SIGNAL(_fromUtf8("doubleClicked(QModelIndex)")), self.pushButtonEditData.click)
        QtCore.QObject.connect(self.treeWidgetGeodesicBase, QtCore.SIGNAL(_fromUtf8("doubleClicked(QModelIndex)")), self.pushButtonEditData.click)
        QtCore.QObject.connect(self.treeWidgetMeansSurvey, QtCore.SIGNAL(_fromUtf8("doubleClicked(QModelIndex)")), self.pushButtonEditData.click)
        QtCore.QObject.connect(self.treeWidgetRealty, QtCore.SIGNAL(_fromUtf8("doubleClicked(QModelIndex)")), self.pushButtonEditData.click)
        QtCore.QObject.connect(self.treeWidgetSubParcel, QtCore.SIGNAL(_fromUtf8("doubleClicked(QModelIndex)")), self.pushButtonEditData.click)
        QtCore.QMetaObject.connectSlotsByName(DialogMP)
        DialogMP.setTabOrder(self.lineEditFind, self.comboBoxFindField)
        DialogMP.setTabOrder(self.comboBoxFindField, self.pushButtonFindMp)
        DialogMP.setTabOrder(self.pushButtonFindMp, self.pushButtonCloseDialog)
        DialogMP.setTabOrder(self.pushButtonCloseDialog, self.spinBoxShemaVersion)
        DialogMP.setTabOrder(self.spinBoxShemaVersion, self.lineEditMpGUID)
        DialogMP.setTabOrder(self.lineEditMpGUID, self.pushButtonEditContractor)
        DialogMP.setTabOrder(self.pushButtonEditContractor, self.textEditReason)
        DialogMP.setTabOrder(self.textEditReason, self.textEditPurpose)
        DialogMP.setTabOrder(self.textEditPurpose, self.comboBoxContractor)
        DialogMP.setTabOrder(self.comboBoxContractor, self.dateEditDateWork)
        DialogMP.setTabOrder(self.dateEditDateWork, self.pushButtonPurpose)
        DialogMP.setTabOrder(self.pushButtonPurpose, self.pushButtonReason)
        DialogMP.setTabOrder(self.pushButtonReason, self.pushButtonAddSectionMp)
        DialogMP.setTabOrder(self.pushButtonAddSectionMp, self.pushButtonSaveData)
        DialogMP.setTabOrder(self.pushButtonSaveData, self.pushButtonEditData)
        DialogMP.setTabOrder(self.pushButtonEditData, self.pushButtonDeleteSectionMp)
        DialogMP.setTabOrder(self.pushButtonDeleteSectionMp, self.pushButtonRefreshData)
        DialogMP.setTabOrder(self.pushButtonRefreshData, self.pushButtonCreateNewMp)
        DialogMP.setTabOrder(self.pushButtonCreateNewMp, self.pushButtonDeleteMp)
        DialogMP.setTabOrder(self.pushButtonDeleteMp, self.comboBoxMp)
        DialogMP.setTabOrder(self.comboBoxMp, self.treeWidget)
        DialogMP.setTabOrder(self.treeWidget, self.tabWidget)
        DialogMP.setTabOrder(self.tabWidget, self.comboBoxEDocCodeType)

    def retranslateUi(self, DialogMP):
        DialogMP.setWindowTitle(QtGui.QApplication.translate("DialogMP", "Межевой план", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(0, QtGui.QApplication.translate("DialogMP", "Разделы межевого плана", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("DialogMP", "<html><head/><body><p align=\"right\">Дата</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("DialogMP", "Тип заявления", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("DialogMP", "Версия схемы", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("DialogMP", "Идентификатор межевого плана", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("DialogMP", "<html><head/><body><p align=\"right\">Создание</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabEDocument), QtGui.QApplication.translate("DialogMP", "Электронный документ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("DialogMP", "<html><head/><body><p>Цель кадастровых<br/>работ</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("DialogMP", "Вид кадастровых<br />работ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DialogMP", "<html><head/><body><p>Кадастровый<br/>инженер</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DialogMP", "<html><head/><body><p>Дата проведения<br />кадастровых работ</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("DialogMP", "Заказчик<br />кадастровых работ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("DialogMP", "Дата приёмки<br />работ", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTitle), QtGui.QApplication.translate("DialogMP", "Титульный лист", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetParcel.setSortingEnabled(True)
        self.treeWidgetParcel.headerItem().setText(0, QtGui.QApplication.translate("DialogMP", "КН", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetParcel.headerItem().setText(1, QtGui.QApplication.translate("DialogMP", "Обозначение", None, QtGui.QApplication.UnicodeUTF8))
        self.labelParcel.setText(QtGui.QApplication.translate("DialogMP", "ЗУ", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPackage), QtGui.QApplication.translate("DialogMP", "Пакет информации", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("DialogMP", "Система<br />координат", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetCoordSystems.setSortingEnabled(True)
        self.treeWidgetCoordSystems.headerItem().setText(0, QtGui.QApplication.translate("DialogMP", "Наименование", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetCoordSystems.headerItem().setText(1, QtGui.QApplication.translate("DialogMP", "Код", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCoordSystems), QtGui.QApplication.translate("DialogMP", "Система координат", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetDocument.setSortingEnabled(True)
        self.treeWidgetDocument.headerItem().setText(0, QtGui.QApplication.translate("DialogMP", "Номер", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetDocument.headerItem().setText(1, QtGui.QApplication.translate("DialogMP", "Наименование", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageDocument), QtGui.QApplication.translate("DialogMP", "Перечень документов, на основании которых подготовлен МП", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetGeodesicBase.setSortingEnabled(True)
        self.treeWidgetGeodesicBase.headerItem().setText(0, QtGui.QApplication.translate("DialogMP", "Название пункта", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageGeodesicBase), QtGui.QApplication.translate("DialogMP", "Сведения о геодезической основе", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetMeansSurvey.setSortingEnabled(True)
        self.treeWidgetMeansSurvey.headerItem().setText(0, QtGui.QApplication.translate("DialogMP", "Название прибора", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageMeansSurvey), QtGui.QApplication.translate("DialogMP", "Сведения о средствах измерения", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetRealty.setSortingEnabled(True)
        self.treeWidgetRealty.headerItem().setText(0, QtGui.QApplication.translate("DialogMP", "Кадастровый номер земельного участка", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageRealty), QtGui.QApplication.translate("DialogMP", "Сведения о наличии зданий, сооружений", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetSubParcel.setSortingEnabled(True)
        self.treeWidgetSubParcel.headerItem().setText(0, QtGui.QApplication.translate("DialogMP", "Кадастровый номер ЗУ", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetSubParcel.headerItem().setText(1, QtGui.QApplication.translate("DialogMP", "Учётный номер ЧЗУ", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageSubParcel), QtGui.QApplication.translate("DialogMP", "Сведения о частях исходных, измененных или уточняемых ЗУ", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabInputData), QtGui.QApplication.translate("DialogMP", "Исходные данные", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("DialogMP", "Файл", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetSurvey.setSortingEnabled(True)
        self.treeWidgetSurvey.headerItem().setText(0, QtGui.QApplication.translate("DialogMP", "Вид файла", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetSurvey.headerItem().setText(1, QtGui.QApplication.translate("DialogMP", "Файл", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSurvey), QtGui.QApplication.translate("DialogMP", "Измерения и расчеты", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabConclusion), QtGui.QApplication.translate("DialogMP", "Заключение КИ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("DialogMP", "Файл", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetSchemeGeodesicPlotting.setSortingEnabled(True)
        self.treeWidgetSchemeGeodesicPlotting.headerItem().setText(0, QtGui.QApplication.translate("DialogMP", "Вид файла", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetSchemeGeodesicPlotting.headerItem().setText(1, QtGui.QApplication.translate("DialogMP", "Файл", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSchemeGeodesicPlotting), QtGui.QApplication.translate("DialogMP", "Схема геопостроений", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("DialogMP", "Файл", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetSchemeDispositionParcels.setSortingEnabled(True)
        self.treeWidgetSchemeDispositionParcels.headerItem().setText(0, QtGui.QApplication.translate("DialogMP", "Вид файла", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetSchemeDispositionParcels.headerItem().setText(1, QtGui.QApplication.translate("DialogMP", "Файл", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDispositionParcels), QtGui.QApplication.translate("DialogMP", "Схема расположения ЗУ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("DialogMP", "Файл", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetDiagramParcels.setSortingEnabled(True)
        self.treeWidgetDiagramParcels.headerItem().setText(0, QtGui.QApplication.translate("DialogMP", "Вид файла", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetDiagramParcels.headerItem().setText(1, QtGui.QApplication.translate("DialogMP", "Файл", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDiagramParcels), QtGui.QApplication.translate("DialogMP", "Чертёж ЗУ и их частей", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("DialogMP", "Файл", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetAgreementDocument.setSortingEnabled(True)
        self.treeWidgetAgreementDocument.headerItem().setText(0, QtGui.QApplication.translate("DialogMP", "Вид файла", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetAgreementDocument.headerItem().setText(1, QtGui.QApplication.translate("DialogMP", "Файл", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAgreementDocument), QtGui.QApplication.translate("DialogMP", "Акт согласования", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("DialogMP", "Файл", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetNodalPointSchemes.setSortingEnabled(True)
        self.treeWidgetNodalPointSchemes.headerItem().setText(0, QtGui.QApplication.translate("DialogMP", "Вид файла", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetNodalPointSchemes.headerItem().setText(1, QtGui.QApplication.translate("DialogMP", "Файл", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabNodalPointSchemes), QtGui.QApplication.translate("DialogMP", "Абрисы", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("DialogMP", "Документ", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetAppendix.setSortingEnabled(True)
        self.treeWidgetAppendix.headerItem().setText(0, QtGui.QApplication.translate("DialogMP", "Номер", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetAppendix.headerItem().setText(1, QtGui.QApplication.translate("DialogMP", "Наименование", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAppendix), QtGui.QApplication.translate("DialogMP", "Приложения", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAddSectionMp.setText(QtGui.QApplication.translate("DialogMP", "Добавить", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSaveData.setText(QtGui.QApplication.translate("DialogMP", "Сохранить", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonEditData.setText(QtGui.QApplication.translate("DialogMP", "Редактировать", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDeleteSectionMp.setText(QtGui.QApplication.translate("DialogMP", "Удалить", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRefreshData.setText(QtGui.QApplication.translate("DialogMP", "Обновить", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCreateNewMp.setText(QtGui.QApplication.translate("DialogMP", "Создать", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDeleteMp.setText(QtGui.QApplication.translate("DialogMP", "Удалить", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCreateXML.setText(QtGui.QApplication.translate("DialogMP", "XML", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("DialogMP", "Искать ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("DialogMP", "в поле", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFindField.setItemText(0, QtGui.QApplication.translate("DialogMP", "КН участка", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFindField.setItemText(1, QtGui.QApplication.translate("DialogMP", "КН входящего участка", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFindField.setItemText(2, QtGui.QApplication.translate("DialogMP", "КН квартала", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFindField.setItemText(3, QtGui.QApplication.translate("DialogMP", "Кадастровый инженер", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFindField.setItemText(4, QtGui.QApplication.translate("DialogMP", "Дата кадастровых работ", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFindField.setItemText(5, QtGui.QApplication.translate("DialogMP", "Вид кадастровых работ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonFindMp.setText(QtGui.QApplication.translate("DialogMP", "Искать", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCloseDialog.setText(QtGui.QApplication.translate("DialogMP", "Закрыть", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
