# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'openlandsettings.ui'
#
# Created: Thu Mar 20 12:46:49 2014
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_OpenLandSettings(object):
    def setupUi(self, OpenLandSettings):
        OpenLandSettings.setObjectName(_fromUtf8("OpenLandSettings"))
        OpenLandSettings.resize(560, 439)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(OpenLandSettings.sizePolicy().hasHeightForWidth())
        OpenLandSettings.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/settings.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        OpenLandSettings.setWindowIcon(icon)
        OpenLandSettings.setSizeGripEnabled(True)
        self.verticalLayout_2 = QtGui.QVBoxLayout(OpenLandSettings)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(OpenLandSettings)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabDataBase = QtGui.QWidget()
        self.tabDataBase.setObjectName(_fromUtf8("tabDataBase"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabDataBase)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBox_2 = QtGui.QGroupBox(self.tabDataBase)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.lineEditProjectFile = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditProjectFile.setObjectName(_fromUtf8("lineEditProjectFile"))
        self.gridLayout.addWidget(self.lineEditProjectFile, 1, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 1, 0, 1, 1)
        self.checkBoxIsUseDefaultConnection = QtGui.QCheckBox(self.groupBox_2)
        self.checkBoxIsUseDefaultConnection.setObjectName(_fromUtf8("checkBoxIsUseDefaultConnection"))
        self.gridLayout.addWidget(self.checkBoxIsUseDefaultConnection, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 3, 0, 1, 1)
        self.lineEditDataBase = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditDataBase.setObjectName(_fromUtf8("lineEditDataBase"))
        self.gridLayout.addWidget(self.lineEditDataBase, 4, 1, 1, 1)
        self.lineEditPort = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditPort.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEditPort.setObjectName(_fromUtf8("lineEditPort"))
        self.gridLayout.addWidget(self.lineEditPort, 3, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 5, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 4, 0, 1, 1)
        self.lineEditUserName = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditUserName.setObjectName(_fromUtf8("lineEditUserName"))
        self.gridLayout.addWidget(self.lineEditUserName, 5, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 6, 0, 1, 1)
        self.lineEditUserPassword = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditUserPassword.setObjectName(_fromUtf8("lineEditUserPassword"))
        self.gridLayout.addWidget(self.lineEditUserPassword, 6, 1, 1, 1)
        self.lineEditServer = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditServer.setObjectName(_fromUtf8("lineEditServer"))
        self.gridLayout.addWidget(self.lineEditServer, 2, 1, 1, 1)
        self.pushButtonFileSelect = QtGui.QPushButton(self.groupBox_2)
        self.pushButtonFileSelect.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/find_search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonFileSelect.setIcon(icon1)
        self.pushButtonFileSelect.setObjectName(_fromUtf8("pushButtonFileSelect"))
        self.gridLayout.addWidget(self.pushButtonFileSelect, 1, 2, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.groupBox_4 = QtGui.QGroupBox(self.tabDataBase)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_4)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.groupBox_4)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.spinBoxVersionXmlMp = QtGui.QSpinBox(self.groupBox_4)
        self.spinBoxVersionXmlMp.setMaximumSize(QtCore.QSize(40, 16777215))
        self.spinBoxVersionXmlMp.setMinimum(4)
        self.spinBoxVersionXmlMp.setMaximum(4)
        self.spinBoxVersionXmlMp.setObjectName(_fromUtf8("spinBoxVersionXmlMp"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinBoxVersionXmlMp)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        self.groupBox_3 = QtGui.QGroupBox(self.tabDataBase)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout.addWidget(self.label_14)
        self.lineEditPathToXmlCreate = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditPathToXmlCreate.setObjectName(_fromUtf8("lineEditPathToXmlCreate"))
        self.horizontalLayout.addWidget(self.lineEditPathToXmlCreate)
        self.pushButtonDirectoryOpen = QtGui.QPushButton(self.groupBox_3)
        self.pushButtonDirectoryOpen.setText(_fromUtf8(""))
        self.pushButtonDirectoryOpen.setIcon(icon1)
        self.pushButtonDirectoryOpen.setObjectName(_fromUtf8("pushButtonDirectoryOpen"))
        self.horizontalLayout.addWidget(self.pushButtonDirectoryOpen)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.tabWidget.addTab(self.tabDataBase, _fromUtf8(""))
        self.tabInterface = QtGui.QWidget()
        self.tabInterface.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabInterface.setObjectName(_fromUtf8("tabInterface"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tabInterface)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.tabInterface)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.radioButtonMultiCont = QtGui.QRadioButton(self.groupBox)
        self.radioButtonMultiCont.setChecked(True)
        self.radioButtonMultiCont.setObjectName(_fromUtf8("radioButtonMultiCont"))
        self.verticalLayout_3.addWidget(self.radioButtonMultiCont)
        self.radioButtonOneCont = QtGui.QRadioButton(self.groupBox)
        self.radioButtonOneCont.setObjectName(_fromUtf8("radioButtonOneCont"))
        self.verticalLayout_3.addWidget(self.radioButtonOneCont)
        self.verticalLayout.addWidget(self.groupBox)
        self.checkBoxIsSortAttributes = QtGui.QCheckBox(self.tabInterface)
        self.checkBoxIsSortAttributes.setChecked(True)
        self.checkBoxIsSortAttributes.setObjectName(_fromUtf8("checkBoxIsSortAttributes"))
        self.verticalLayout.addWidget(self.checkBoxIsSortAttributes)
        self.checkBoxIsPointsShow = QtGui.QCheckBox(self.tabInterface)
        self.checkBoxIsPointsShow.setChecked(True)
        self.checkBoxIsPointsShow.setObjectName(_fromUtf8("checkBoxIsPointsShow"))
        self.verticalLayout.addWidget(self.checkBoxIsPointsShow)
        self.checkBoxIsShowOnlyUserData = QtGui.QCheckBox(self.tabInterface)
        self.checkBoxIsShowOnlyUserData.setChecked(True)
        self.checkBoxIsShowOnlyUserData.setObjectName(_fromUtf8("checkBoxIsShowOnlyUserData"))
        self.verticalLayout.addWidget(self.checkBoxIsShowOnlyUserData)
        self.tabWidget.addTab(self.tabInterface, _fromUtf8(""))
        self.tabCoordSystem = QtGui.QWidget()
        self.tabCoordSystem.setObjectName(_fromUtf8("tabCoordSystem"))
        self.formLayout_3 = QtGui.QFormLayout(self.tabCoordSystem)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_7 = QtGui.QLabel(self.tabCoordSystem)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.comboBoxMSK = QtGui.QComboBox(self.tabCoordSystem)
        self.comboBoxMSK.setObjectName(_fromUtf8("comboBoxMSK"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBoxMSK)
        self.tabWidget.addTab(self.tabCoordSystem, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(OpenLandSettings)
        self.buttonBox.setEnabled(True)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(OpenLandSettings)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), OpenLandSettings.reject)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), OpenLandSettings.accept)
        QtCore.QMetaObject.connectSlotsByName(OpenLandSettings)
        OpenLandSettings.setTabOrder(self.radioButtonMultiCont, self.radioButtonOneCont)
        OpenLandSettings.setTabOrder(self.radioButtonOneCont, self.checkBoxIsSortAttributes)
        OpenLandSettings.setTabOrder(self.checkBoxIsSortAttributes, self.checkBoxIsPointsShow)
        OpenLandSettings.setTabOrder(self.checkBoxIsPointsShow, self.checkBoxIsShowOnlyUserData)
        OpenLandSettings.setTabOrder(self.checkBoxIsShowOnlyUserData, self.checkBoxIsUseDefaultConnection)
        OpenLandSettings.setTabOrder(self.checkBoxIsUseDefaultConnection, self.lineEditProjectFile)
        OpenLandSettings.setTabOrder(self.lineEditProjectFile, self.pushButtonFileSelect)
        OpenLandSettings.setTabOrder(self.pushButtonFileSelect, self.lineEditServer)
        OpenLandSettings.setTabOrder(self.lineEditServer, self.lineEditPort)
        OpenLandSettings.setTabOrder(self.lineEditPort, self.lineEditDataBase)
        OpenLandSettings.setTabOrder(self.lineEditDataBase, self.lineEditUserName)
        OpenLandSettings.setTabOrder(self.lineEditUserName, self.lineEditUserPassword)
        OpenLandSettings.setTabOrder(self.lineEditUserPassword, self.spinBoxVersionXmlMp)
        OpenLandSettings.setTabOrder(self.spinBoxVersionXmlMp, self.lineEditPathToXmlCreate)
        OpenLandSettings.setTabOrder(self.lineEditPathToXmlCreate, self.pushButtonDirectoryOpen)
        OpenLandSettings.setTabOrder(self.pushButtonDirectoryOpen, self.comboBoxMSK)
        OpenLandSettings.setTabOrder(self.comboBoxMSK, self.tabWidget)
        OpenLandSettings.setTabOrder(self.tabWidget, self.buttonBox)

    def retranslateUi(self, OpenLandSettings):
        OpenLandSettings.setWindowTitle(_translate("OpenLandSettings", "Настройки openLand", None))
        self.groupBox_2.setTitle(_translate("OpenLandSettings", "Базовый проект и параметры БД", None))
        self.label_8.setText(_translate("OpenLandSettings", "Сервер", None))
        self.lineEditProjectFile.setText(_translate("OpenLandSettings", "Не указан", None))
        self.label_13.setText(_translate("OpenLandSettings", "Автоматически обновляемый<br />файл проекта", None))
        self.checkBoxIsUseDefaultConnection.setText(_translate("OpenLandSettings", "Использовать для обновления проекта openLand.qgs", None))
        self.label_9.setText(_translate("OpenLandSettings", "Порт", None))
        self.lineEditDataBase.setText(_translate("OpenLandSettings", "openland", None))
        self.lineEditPort.setText(_translate("OpenLandSettings", "5432", None))
        self.label_11.setText(_translate("OpenLandSettings", "Пользователь", None))
        self.label_10.setText(_translate("OpenLandSettings", "База данных", None))
        self.lineEditUserName.setText(_translate("OpenLandSettings", "openlanduser1", None))
        self.label_12.setText(_translate("OpenLandSettings", "Пароль", None))
        self.lineEditUserPassword.setText(_translate("OpenLandSettings", "user1pass", None))
        self.lineEditServer.setText(_translate("OpenLandSettings", "localhost", None))
        self.groupBox_4.setTitle(_translate("OpenLandSettings", "XML схемы", None))
        self.label.setText(_translate("OpenLandSettings", "Номер версии XML схемы межевого плана", None))
        self.groupBox_3.setTitle(_translate("OpenLandSettings", "Каталоги, используемые по умолчанию", None))
        self.label_14.setText(_translate("OpenLandSettings", "<html><head/><body><p align=\"right\">Каталог для создаваемых<br />XML файлов МП</p></body></html>", None))
        self.lineEditPathToXmlCreate.setText(_translate("OpenLandSettings", "Не указан", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDataBase), _translate("OpenLandSettings", "Данные", None))
        self.groupBox.setTitle(_translate("OpenLandSettings", "При выборе одного полигона слоя  «Участок» производить операции с", None))
        self.radioButtonMultiCont.setText(_translate("OpenLandSettings", "Земельным участком полностью", None))
        self.radioButtonOneCont.setText(_translate("OpenLandSettings", "Только выбранным контуром МЗУ (входящим в ЕЗП, ЧЗУ)", None))
        self.checkBoxIsSortAttributes.setText(_translate("OpenLandSettings", "Сортировать атрибуты земельного участка в списке ", None))
        self.checkBoxIsPointsShow.setText(_translate("OpenLandSettings", "Отображать точки и границы ЗУ в списке окна атрибутов", None))
        self.checkBoxIsShowOnlyUserData.setText(_translate("OpenLandSettings", "Отображать МП и документы только текущего пользователя БД", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabInterface), _translate("OpenLandSettings", "Интерфейс", None))
        self.label_7.setText(_translate("OpenLandSettings", "Система координат", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCoordSystem), _translate("OpenLandSettings", "Система координат", None))

import resources_rc
