# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'point.ui'
#
# Created: Mon Oct 28 11:22:37 2013
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Point(object):
    def setupUi(self, Point):
        Point.setObjectName(_fromUtf8("Point"))
        Point.resize(500, 220)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/point.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Point.setWindowIcon(icon)
        Point.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(Point)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.spinBoxNumber = QtGui.QSpinBox(Point)
        self.spinBoxNumber.setMinimumSize(QtCore.QSize(150, 0))
        self.spinBoxNumber.setMaximum(999999)
        self.spinBoxNumber.setObjectName(_fromUtf8("spinBoxNumber"))
        self.gridLayout.addWidget(self.spinBoxNumber, 0, 3, 1, 1)
        self.pushButtonClose = QtGui.QPushButton(Point)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/close.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonClose.setIcon(icon1)
        self.pushButtonClose.setObjectName(_fromUtf8("pushButtonClose"))
        self.gridLayout.addWidget(self.pushButtonClose, 6, 3, 1, 1)
        self.spinBoxOrder = QtGui.QSpinBox(Point)
        self.spinBoxOrder.setMinimumSize(QtCore.QSize(150, 0))
        self.spinBoxOrder.setMaximum(999999)
        self.spinBoxOrder.setObjectName(_fromUtf8("spinBoxOrder"))
        self.gridLayout.addWidget(self.spinBoxOrder, 1, 3, 1, 1)
        self.label_3 = QtGui.QLabel(Point)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 2, 1, 1)
        self.lineEditMeasureError = QtGui.QLineEdit(Point)
        self.lineEditMeasureError.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEditMeasureError.setObjectName(_fromUtf8("lineEditMeasureError"))
        self.gridLayout.addWidget(self.lineEditMeasureError, 3, 1, 1, 1)
        self.label_2 = QtGui.QLabel(Point)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.lineEditY = QtGui.QLineEdit(Point)
        self.lineEditY.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEditY.setObjectName(_fromUtf8("lineEditY"))
        self.gridLayout.addWidget(self.lineEditY, 2, 1, 1, 1)
        self.comboBoxMethod = QtGui.QComboBox(Point)
        self.comboBoxMethod.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBoxMethod.setObjectName(_fromUtf8("comboBoxMethod"))
        self.gridLayout.addWidget(self.comboBoxMethod, 2, 3, 1, 1)
        self.comboBoxWay2Fix = QtGui.QComboBox(Point)
        self.comboBoxWay2Fix.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBoxWay2Fix.setObjectName(_fromUtf8("comboBoxWay2Fix"))
        self.gridLayout.addWidget(self.comboBoxWay2Fix, 3, 3, 1, 1)
        self.label_5 = QtGui.QLabel(Point)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.checkBoxUpdateGeom = QtGui.QCheckBox(Point)
        self.checkBoxUpdateGeom.setMaximumSize(QtCore.QSize(150, 16777215))
        self.checkBoxUpdateGeom.setObjectName(_fromUtf8("checkBoxUpdateGeom"))
        self.gridLayout.addWidget(self.checkBoxUpdateGeom, 5, 1, 1, 1)
        self.label_7 = QtGui.QLabel(Point)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 3, 2, 1, 1)
        self.lineEditX = QtGui.QLineEdit(Point)
        self.lineEditX.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEditX.setObjectName(_fromUtf8("lineEditX"))
        self.gridLayout.addWidget(self.lineEditX, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(Point)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 2, 2, 1, 1)
        self.label = QtGui.QLabel(Point)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.lineEditPrefix = QtGui.QLineEdit(Point)
        self.lineEditPrefix.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEditPrefix.setObjectName(_fromUtf8("lineEditPrefix"))
        self.gridLayout.addWidget(self.lineEditPrefix, 0, 1, 1, 1)
        self.pushButtonSave = QtGui.QPushButton(Point)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonSave.setIcon(icon2)
        self.pushButtonSave.setObjectName(_fromUtf8("pushButtonSave"))
        self.gridLayout.addWidget(self.pushButtonSave, 6, 1, 1, 1)
        self.label_6 = QtGui.QLabel(Point)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_4 = QtGui.QLabel(Point)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.checkBoxIsPre = QtGui.QCheckBox(Point)
        self.checkBoxIsPre.setEnabled(False)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.checkBoxIsPre.setFont(font)
        self.checkBoxIsPre.setCheckable(True)
        self.checkBoxIsPre.setObjectName(_fromUtf8("checkBoxIsPre"))
        self.gridLayout.addWidget(self.checkBoxIsPre, 4, 1, 1, 1)
        self.label_9 = QtGui.QLabel(Point)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 4, 2, 1, 1)
        self.comboBoxCorrectPoint = QtGui.QComboBox(Point)
        self.comboBoxCorrectPoint.setEnabled(False)
        self.comboBoxCorrectPoint.setObjectName(_fromUtf8("comboBoxCorrectPoint"))
        self.gridLayout.addWidget(self.comboBoxCorrectPoint, 4, 3, 1, 1)

        self.retranslateUi(Point)
        QtCore.QMetaObject.connectSlotsByName(Point)
        Point.setTabOrder(self.lineEditPrefix, self.spinBoxNumber)
        Point.setTabOrder(self.spinBoxNumber, self.lineEditX)
        Point.setTabOrder(self.lineEditX, self.spinBoxOrder)
        Point.setTabOrder(self.spinBoxOrder, self.lineEditY)
        Point.setTabOrder(self.lineEditY, self.comboBoxMethod)
        Point.setTabOrder(self.comboBoxMethod, self.lineEditMeasureError)
        Point.setTabOrder(self.lineEditMeasureError, self.comboBoxWay2Fix)
        Point.setTabOrder(self.comboBoxWay2Fix, self.checkBoxIsPre)
        Point.setTabOrder(self.checkBoxIsPre, self.comboBoxCorrectPoint)
        Point.setTabOrder(self.comboBoxCorrectPoint, self.checkBoxUpdateGeom)
        Point.setTabOrder(self.checkBoxUpdateGeom, self.pushButtonSave)
        Point.setTabOrder(self.pushButtonSave, self.pushButtonClose)

    def retranslateUi(self, Point):
        Point.setWindowTitle(QtGui.QApplication.translate("Point", "Атрибуты точки", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonClose.setText(QtGui.QApplication.translate("Point", "Отмена", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Point", "<html><head/><body><p align=\"right\">Порядок<br/>обхода</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Point", "Координата Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Point", "<html><head/><body><p align=\"right\">Префикс<br/>номера</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxUpdateGeom.setText(QtGui.QApplication.translate("Point", "Обновить геометрию", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Point", "<html><head/><body><p align=\"right\">Способ<br/>закрепления</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Point", "<html><head/><body><p align=\"right\">Метод<br/>определения</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Point", "Координата X", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSave.setText(QtGui.QApplication.translate("Point", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Point", "Погрешность", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Point", "<html><head/><body><p align=\"right\">Номер</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxIsPre.setText(QtGui.QApplication.translate("Point", "Прекратившая существование", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Point", "<html><head/><body><p align=\"right\">Уточненная<br/>точка</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
