# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'realty.ui'
#
# Created: Mon Oct 28 11:22:38 2013
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_DialogRealty(object):
    def setupUi(self, DialogRealty):
        DialogRealty.setObjectName(_fromUtf8("DialogRealty"))
        DialogRealty.resize(520, 360)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/home.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogRealty.setWindowIcon(icon)
        DialogRealty.setSizeGripEnabled(True)
        DialogRealty.setModal(True)
        self.verticalLayout = QtGui.QVBoxLayout(DialogRealty)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.treeWidget = QtGui.QTreeWidget(DialogRealty)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.verticalLayout.addWidget(self.treeWidget)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(DialogRealty)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.lineEditCadastralNumber = QtGui.QLineEdit(DialogRealty)
        self.lineEditCadastralNumber.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditCadastralNumber.setInputMask(_fromUtf8(""))
        self.lineEditCadastralNumber.setObjectName(_fromUtf8("lineEditCadastralNumber"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditCadastralNumber)
        self.label_2 = QtGui.QLabel(DialogRealty)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.lineEditCadastralNumberOtherNumber = QtGui.QLineEdit(DialogRealty)
        self.lineEditCadastralNumberOtherNumber.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditCadastralNumberOtherNumber.setObjectName(_fromUtf8("lineEditCadastralNumberOtherNumber"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditCadastralNumberOtherNumber)
        self.label_3 = QtGui.QLabel(DialogRealty)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.lineEditNameOKS = QtGui.QLineEdit(DialogRealty)
        self.lineEditNameOKS.setInputMask(_fromUtf8(""))
        self.lineEditNameOKS.setObjectName(_fromUtf8("lineEditNameOKS"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditNameOKS)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButtonSelect = QtGui.QPushButton(DialogRealty)
        self.pushButtonSelect.setEnabled(False)
        self.pushButtonSelect.setStatusTip(_fromUtf8(""))
        self.pushButtonSelect.setWhatsThis(_fromUtf8(""))
        self.pushButtonSelect.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/symbol_check.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonSelect.setIcon(icon1)
        self.pushButtonSelect.setAutoDefault(False)
        self.pushButtonSelect.setDefault(True)
        self.pushButtonSelect.setObjectName(_fromUtf8("pushButtonSelect"))
        self.horizontalLayout.addWidget(self.pushButtonSelect)
        self.pushButtonAdd = QtGui.QPushButton(DialogRealty)
        self.pushButtonAdd.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/symbol_add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonAdd.setIcon(icon2)
        self.pushButtonAdd.setAutoDefault(False)
        self.pushButtonAdd.setObjectName(_fromUtf8("pushButtonAdd"))
        self.horizontalLayout.addWidget(self.pushButtonAdd)
        self.pushButtonEdit = QtGui.QPushButton(DialogRealty)
        self.pushButtonEdit.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/edit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonEdit.setIcon(icon3)
        self.pushButtonEdit.setAutoDefault(False)
        self.pushButtonEdit.setObjectName(_fromUtf8("pushButtonEdit"))
        self.horizontalLayout.addWidget(self.pushButtonEdit)
        self.pushButtonDel = QtGui.QPushButton(DialogRealty)
        self.pushButtonDel.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/symbol_remove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonDel.setIcon(icon4)
        self.pushButtonDel.setAutoDefault(False)
        self.pushButtonDel.setObjectName(_fromUtf8("pushButtonDel"))
        self.horizontalLayout.addWidget(self.pushButtonDel)
        self.pushButtonSave = QtGui.QPushButton(DialogRealty)
        self.pushButtonSave.setEnabled(False)
        self.pushButtonSave.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonSave.setIcon(icon5)
        self.pushButtonSave.setAutoDefault(False)
        self.pushButtonSave.setObjectName(_fromUtf8("pushButtonSave"))
        self.horizontalLayout.addWidget(self.pushButtonSave)
        self.pushButtonRefresh = QtGui.QPushButton(DialogRealty)
        self.pushButtonRefresh.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonRefresh.setIcon(icon6)
        self.pushButtonRefresh.setAutoDefault(False)
        self.pushButtonRefresh.setObjectName(_fromUtf8("pushButtonRefresh"))
        self.horizontalLayout.addWidget(self.pushButtonRefresh)
        self.pushButtonClose = QtGui.QPushButton(DialogRealty)
        self.pushButtonClose.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/openland/icons/close.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonClose.setIcon(icon7)
        self.pushButtonClose.setAutoDefault(False)
        self.pushButtonClose.setObjectName(_fromUtf8("pushButtonClose"))
        self.horizontalLayout.addWidget(self.pushButtonClose)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.labelMessage = QtGui.QLabel(DialogRealty)
        self.labelMessage.setText(_fromUtf8(""))
        self.labelMessage.setObjectName(_fromUtf8("labelMessage"))
        self.verticalLayout.addWidget(self.labelMessage)

        self.retranslateUi(DialogRealty)
        QtCore.QMetaObject.connectSlotsByName(DialogRealty)
        DialogRealty.setTabOrder(self.treeWidget, self.lineEditCadastralNumber)
        DialogRealty.setTabOrder(self.lineEditCadastralNumber, self.lineEditCadastralNumberOtherNumber)
        DialogRealty.setTabOrder(self.lineEditCadastralNumberOtherNumber, self.lineEditNameOKS)
        DialogRealty.setTabOrder(self.lineEditNameOKS, self.pushButtonSelect)
        DialogRealty.setTabOrder(self.pushButtonSelect, self.pushButtonAdd)
        DialogRealty.setTabOrder(self.pushButtonAdd, self.pushButtonEdit)
        DialogRealty.setTabOrder(self.pushButtonEdit, self.pushButtonDel)
        DialogRealty.setTabOrder(self.pushButtonDel, self.pushButtonSave)
        DialogRealty.setTabOrder(self.pushButtonSave, self.pushButtonRefresh)
        DialogRealty.setTabOrder(self.pushButtonRefresh, self.pushButtonClose)

    def retranslateUi(self, DialogRealty):
        DialogRealty.setWindowTitle(QtGui.QApplication.translate("DialogRealty", "Объект капитального строительства", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.setSortingEnabled(True)
        self.treeWidget.headerItem().setText(0, QtGui.QApplication.translate("DialogRealty", "КН ЗУ", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(1, QtGui.QApplication.translate("DialogRealty", "КН ОКС", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DialogRealty", "Кадастровый номер<br />земельного участка", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DialogRealty", "Кадастровые или иные номера<br />зданий, сооружений", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("DialogRealty", "Наименование (вид) расположенных<br />на ЗУ объектов недвижимости", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSelect.setToolTip(QtGui.QApplication.translate("DialogRealty", "Выбрать ОКС", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAdd.setToolTip(QtGui.QApplication.translate("DialogRealty", "Добавить ОКС", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonEdit.setToolTip(QtGui.QApplication.translate("DialogRealty", "Редактировать атрибуты ОКС", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDel.setToolTip(QtGui.QApplication.translate("DialogRealty", "Удалить ОКС", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSave.setToolTip(QtGui.QApplication.translate("DialogRealty", "Сохранить атрибуты ОКС", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRefresh.setToolTip(QtGui.QApplication.translate("DialogRealty", "Обновить атрибуты ОКС", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonClose.setToolTip(QtGui.QApplication.translate("DialogRealty", "Закрыть окно", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
